// Code generated by mockery v2.44.1. DO NOT EDIT.

package repomocks

import (
	domain "Task_Manager/domain"

	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// TaskRepository is an autogenerated mock type for the TaskRepository type
type TaskRepository struct {
	mock.Mock
}

// DeleteTask provides a mock function with given fields: id, isAdmin, userId
func (_m *TaskRepository) DeleteTask(id primitive.ObjectID, isAdmin string, userId primitive.ObjectID) error {
	ret := _m.Called(id, isAdmin, userId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(primitive.ObjectID, string, primitive.ObjectID) error); ok {
		r0 = rf(id, isAdmin, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTaskById provides a mock function with given fields: id, isAdmin, userId
func (_m *TaskRepository) GetTaskById(id primitive.ObjectID, isAdmin string, userId primitive.ObjectID) (domain.Task, error) {
	ret := _m.Called(id, isAdmin, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskById")
	}

	var r0 domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(primitive.ObjectID, string, primitive.ObjectID) (domain.Task, error)); ok {
		return rf(id, isAdmin, userId)
	}
	if rf, ok := ret.Get(0).(func(primitive.ObjectID, string, primitive.ObjectID) domain.Task); ok {
		r0 = rf(id, isAdmin, userId)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}

	if rf, ok := ret.Get(1).(func(primitive.ObjectID, string, primitive.ObjectID) error); ok {
		r1 = rf(id, isAdmin, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTasks provides a mock function with given fields: isAdmin, userId
func (_m *TaskRepository) GetTasks(isAdmin string, userId primitive.ObjectID) ([]domain.Task, error) {
	ret := _m.Called(isAdmin, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetTasks")
	}

	var r0 []domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(string, primitive.ObjectID) ([]domain.Task, error)); ok {
		return rf(isAdmin, userId)
	}
	if rf, ok := ret.Get(0).(func(string, primitive.ObjectID) []domain.Task); ok {
		r0 = rf(isAdmin, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(string, primitive.ObjectID) error); ok {
		r1 = rf(isAdmin, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostTask provides a mock function with given fields: newTask
func (_m *TaskRepository) PostTask(newTask domain.Task) error {
	ret := _m.Called(newTask)

	if len(ret) == 0 {
		panic("no return value specified for PostTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Task) error); ok {
		r0 = rf(newTask)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PutTask provides a mock function with given fields: updatedTask, id, isAdmin, userId
func (_m *TaskRepository) PutTask(updatedTask domain.Task, id primitive.ObjectID, isAdmin string, userId primitive.ObjectID) error {
	ret := _m.Called(updatedTask, id, isAdmin, userId)

	if len(ret) == 0 {
		panic("no return value specified for PutTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Task, primitive.ObjectID, string, primitive.ObjectID) error); ok {
		r0 = rf(updatedTask, id, isAdmin, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTaskRepository creates a new instance of TaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskRepository {
	mock := &TaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
